spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:55433/asterion_auth
    username: asterion
    password: asterion

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.security: info

asterion:
  security:
    jwt:
      secret: ${JWT_SECRET:change-me-change-me-change-me-change-me}
      access-token-expiration-seconds: 3600
      refresh-token-expiration-seconds: 2592000

    bootstrap-admin:
      enabled: true
      email: admin@asterion.com
      password: ${ASTERION_BOOTSTRAP_ADMIN_PASSWORD}